apiVersion: automation.cloudbees.io/v1alpha1
kind: Workflow

name: user-account-service-ci

on:
  push:
    branches:
      - main
      - develop
      - "feature/**"

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Setup Java
        uses: cloudbees-io/setup-java@v1
        with:
          java-version: "17"
          distribution: temurin

      - name: Build
        run: mvn clean compile

      - name: Test
        run: mvn test

      - name: Package
        run: mvn package -DskipTests
